language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - "npm run build"

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "0.8"
